networks:
  demotestapp:

services:
  angular:
    build:
      context: ./Client
      dockerfile: Dockerfile
    volumes:
      - ./Client:/app
      - /app/node_modules
    ports:
      - 4200:4200
    depends_on:
      - dotnet
    environment:
      - CHOKIDAR_USEPOLLING=true

  dotnet:
    build:
      context: ./Api/DemoApi
      dockerfile: Dockerfile
    ports:
      - 8001:80
    volumes:
      - ./Api/DemoApi:/src
    depends_on:
      - sqlserver
    environment:
      - DB_HOST=sqlserver
      - DB_NAME=DemoApiDb
      - DB_SA_PASSWORD=password@12345#
    networks: 
      - demotestapp

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - SA_PASSWORD=password@12345#
      - ACCEPT_EULA=Y
    ports:
      - 8002:1433
    volumes:
      - sqlserverdata:/var/opt/mssql
    networks: 
      - demotestapp

volumes:
  sqlserverdata: