services:
  angular:
    build:
      context: ./Client
      dockerfile: Dockerfile
    volumes:
      - ./Client:/app
      - /app/node_modules
    ports:
      - "4200:4200"
    environment:
      - CHOKIDAR_USEPOLLING=true

  dotnet:
    build:
      context: ./Api/DemoApi
      dockerfile: Dockerfile
    ports:
      - "5027:5027"
    volumes:
      - ./Api/DemoApi:/src
    command: dotnet watch run --urls http://0.0.0.0:5027
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
    depends_on:
      - sqlserver

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "YourStrong!Passw0rd"  # à changer avec un mot de passe fort
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - sqlserverdata:/var/opt/mssql

volumes:
  sqlserverdata: